# Generated by Django 4.2.13 on 2026-06-12 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPBenchmarkPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_date', models.DateField(unique=True)),
                ('nifty50_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nifty500_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nifty50_cmp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nifty500_cmp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['week_date'],
            },
        ),
        migrations.CreateModel(
            name='SIPPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('price_date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_stale', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIPWeeklySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_date', models.DateField()),
                ('weekly_buy', models.DecimalField(decimal_places=4, max_digits=14)),
                ('exits_recycled', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('fresh_cash', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cumulative_fresh', models.DecimalField(decimal_places=4, max_digits=14)),
                ('portfolio_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_date'],
            },
        ),
        migrations.CreateModel(
            name='SIPTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_date', models.DateField()),
                ('etf_name', models.CharField(max_length=100)),
                ('asset_class', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('trade_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('exit_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['trade_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='sippricecache',
            constraint=models.UniqueConstraint(fields=('ticker', 'price_date'), name='unique_sip_price_cache'),
        ),
        migrations.AddConstraint(
            model_name='sipweeklysnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'week_date'), name='unique_sip_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='siptrade',
            constraint=models.UniqueConstraint(fields=('user', 'trade_date', 'ticker', 'qty', 'price'), name='unique_sip_trade'),
        ),
    ]
