# Generated by Django 4.2.13 on 2026-05-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TRADING', 'Trading'), ('ETF', 'ETF')], default='TRADING', max_length=20)),
                ('starting_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('worst_case_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
    ]
