# Generated by Django 4.2.13 on 2026-05-17 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scrip_name', models.CharField(max_length=255)),
                ('segment', models.CharField(choices=[('EQUITY', 'Equity'), ('COMMODITY', 'Commodity'), ('F_AND_O', 'F&O')], max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=10)),
                ('legs', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('initial_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('gross_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'entry_date'], name='trades_portfol_4eb8f4_idx'), models.Index(fields=['portfolio', 'close_date'], name='trades_portfol_a913d2_idx'), models.Index(fields=['portfolio', 'segment'], name='trades_portfol_84bc12_idx')],
            },
        ),
    ]
