# Generated by Django 4.2.13 on 2026-05-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=100)),
                ('fund_house', models.CharField(max_length=255)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_folios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mf_folios',
                'ordering': ['fund_house', 'folio_number'],
                'unique_together': {('user', 'folio_number')},
            },
        ),
        migrations.CreateModel(
            name='MFScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=500)),
                ('scheme_code', models.CharField(blank=True, max_length=50)),
                ('isin', models.CharField(blank=True, max_length=30)),
                ('registrar', models.CharField(blank=True, max_length=50)),
                ('plan', models.CharField(choices=[('DIRECT', 'Direct'), ('REGULAR', 'Regular')], default='DIRECT', max_length=10)),
                ('option', models.CharField(choices=[('GROWTH', 'Growth'), ('IDCW', 'IDCW / Dividend')], default='GROWTH', max_length=10)),
                ('closing_units', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('closing_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('closing_nav_date', models.DateField(blank=True, null=True)),
                ('cost_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='mf.mffolio')),
            ],
            options={
                'db_table': 'mf_schemes',
                'ordering': ['scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='MFTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('SIP', 'SIP'), ('PURCHASE', 'Purchase'), ('REDEMPTION', 'Redemption'), ('SWITCH_IN', 'Switch In'), ('SWITCH_OUT', 'Switch Out'), ('DIVIDEND', 'Dividend / IDCW'), ('BONUS', 'Bonus'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('units', models.DecimalField(decimal_places=4, max_digits=18)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mf.mfscheme')),
            ],
            options={
                'db_table': 'mf_transactions',
                'ordering': ['transaction_date'],
                'unique_together': {('scheme', 'transaction_date', 'amount', 'units')},
            },
        ),
    ]
